name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-request-job:
    runs-on : ubuntu-latest
    
    defaults:
      run:
        working-directory: ./typescript-project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Nodejs
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'
          cache-dependency-path: ./typescript-project/yarn.lock

      # Install Yarn
      # - name: Install Yarn
      #   run: npm install --global yarn

      #Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      # Run linting
      - name: Run linting
        run: yarn lint
      
      # compile the code
      - name: Build project
        run: yarn build

      # Run tests
      - name: Run tests
        run: yarn test